name: shjanken 
description: I WRITE CODE. FOR THE BEST LIFE! 
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://shjanken.github.io'
author:         'shjanken'
